In [11]:
import numpy as np
numbers=np.array(range(1,11),copy=True)
numbers

#2행 4열 행렬을(배열) 만들고 0으로 초기화한 초기 배열을 생성
zeros = np.zeros([2,4], dtype=np.float64)
zeros

# 생성시 크기 반환
zeros.shape
#행 반환 위와 같음
numbers.ndim


arr1=np.array([9,11,-3,-6,3,42,22,-10])
bool1= arr1>0
bool1
print(arr1[bool1])



[ 9 11  3 42 22]


TypeError: '>' not supported between instances of 'list' and 'int'

In [3]:
eye= np.eye(5,k=0, dtype=np.float64)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# 일정한 간격으로 배열된 배열을 만듬. 쓸만하네
Spacearr=np.arange(2, 20 , 2)
Spacearr
print(" = %d" % (Spacearr[1]+Spacearr[1]) )
IntSpacarr= Spacearr.astype(np.int)
IntSpacarr[0]+IntSpacarr[1]



 = 8


6

In [4]:
Dic13=dict(a="Gi",b="Gd")
print(Dic13)

{'a': 'Gi', 'b': 'Gd'}


In [5]:
print("3"*10)
print("="*50)
aa="="*50
len(aa)
str="life is Shit baby."
str[1:5]

3333333333


'ife '

In [8]:
#그냥 더하면 된다.
a=np.arange(4)
print(a)
b=np.arange(1,5)
print(b)
print(a+b)
print("a*b" , a*b )

[0 1 2 3]
[1 2 3 4]
[1 3 5 7]
a*b [ 0  2  6 12]


In [9]:
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 99.19, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11, 30.22, 30.91])
stocks

array([140.49,   0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 ,  99.19,
       109.96, 111.47,  35.71,  36.27,  87.85,  89.11,  30.22,  30.91])

In [10]:
#비슷한 값끼리 모음
stocks = stocks.reshape(8, 2).T
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.97,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

In [11]:
fall = np.greater(stocks[0], stocks[1])
fall


array([ True, False, False, False, False, False, False, False])

In [18]:
stocks[1,0]=np.nan
np.isnan(stocks)
stocks[np.isnan(stocks)]=0
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.  ,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])