In [21]:
import numpy as np
numbers=np.array(range(1,11),copy=True)
numbers

#2행 4열 행렬을(배열) 만들고 0으로 초기화한 초기 배열을 생성
zeros = np.zeros([2,4], dtype=np.float64)
zeros

# 생성시 크기 반환
zeros.shape
#행 반환 위와 같음
numbers.ndim


arr1=np.array([9,11,-3,-6,3,42,22,-10])
bool1= arr1>0
bool1
print(arr1[bool1])



[ 9 11  3 42 22]


In [22]:
eye= np.eye(5,k=0, dtype=np.float64)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# 일정한 간격으로 배열된 배열을 만듬. 쓸만하네
Spacearr=np.arange(2, 20 , 2)
Spacearr
print(" = %d" % (Spacearr[1]+Spacearr[1]) )
IntSpacarr= Spacearr.astype(np.int)
IntSpacarr[0]+IntSpacarr[1]



 = 8


6

In [24]:
Dic13=dict(a="Gi",b="Gd")
print(Dic13)

{'a': 'Gi', 'b': 'Gd'}


In [25]:
print("3"*10)
print("="*50)
aa="="*50
len(aa)
str="life is Shit baby."
str[1:5]

3333333333


'ife '

In [26]:
#그냥 더하면 된다.
a=np.arange(4)
print(a)
b=np.arange(1,5)
print(b)
print(a+b)
print("a*b" , a*b )

[0 1 2 3]
[1 2 3 4]
[1 3 5 7]
a*b [ 0  2  6 12]


In [27]:
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2,
                   99.19, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11, 30.22, 30.91])
stocks

array([140.49,   0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 ,  99.19,
       109.96, 111.47,  35.71,  36.27,  87.85,  89.11,  30.22,  30.91])

In [28]:
#비슷한 값끼리 모음
stocks = stocks.reshape(8, 2).T #2행 8열
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.97,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

In [29]:
fall = np.greater(stocks[0], stocks[1])
fall


array([ True, False, False, False, False, False, False, False])

In [30]:
stocks[1,0]=np.nan
np.isnan(stocks)
stocks[np.isnan(stocks)]=0
stocks

array([[140.49,  40.68,  55.7 ,  98.2 , 109.96,  35.71,  87.85,  30.22],
       [  0.  ,  41.53,  57.21,  99.19, 111.47,  36.27,  89.11,  30.91]])

In [31]:
#어느 주식의 가격이 눈에 띄게 변화했는지 알아보기 위해 작은 가격(1.00달러 미만) 변동을
#0으ㅡ로 바꾸고, 0이 아닌 엘리먼트를 찾음.

#3항 연산자 사용. 앞이 조건 , 2번째 매개변수는 true일 때, 3번째 매개변수는 false 일때
changes=np.where(np.abs(stocks[1]-stocks[0]) > 1.00, stocks[1] - stocks[0],0 )
changes

sap= np.array(["MMM","ABT","ABBV","ACN","ACE","ATVI","ADBE","ADT"])
sap[np.nonzero(changes)] # 0이 아닌 해당 주식명만 반환


#같은 방법
sap=sap[np.abs(stocks[1] - stocks[0]) > 1.00 ]
print(sap)


['MMM' 'ABBV' 'ACE' 'ADBE']


In [32]:
#평균수준보다 크게 변화한 주식 찾기
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2,
                   99.19, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11, 30.22, 30.91])
sap= np.array(["MMM","ABT","ABBV","ACN","ACE","ATVI","ADBE","ADT"])

print(np.mean(np.abs(stocks[0] - stocks[1])) )

sap[stocks[1]]


139.52


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

# This is a partial listing
RATE = .0375
TERM = 30
simple =   (     RATE  * np.ones(TERM)).cumsum()
compound = ((1 + RATE) * np.ones(TERM)).cumprod() - 1

matplotlib.style.use("ggplot")
t = np.arange(1, 31)
plt.plot(t, compound)
plt.plot(t, simple)
plt.legend(["Compound", "Simple"], loc=2)
plt.xlabel("Year")
plt.ylabel("Accrued Interest")
plt.tight_layout()
plt.savefig("interest.pdf")

In [35]:
dna="AGTCCGCGAATACAGGCTCGGT"
dna_as_array=np.array(list(dna))
dna_as_array

#중복되지 않은 엘리먼트 찾기
np.unique(dna_as_array)

#sap 배열에서 엘리먼트 찾기
np.in1d(["MSFT","MMM","AAPL"],sap)

array([False,  True, False])

In [40]:
#.npy 파일로 저장하기
np.save("sap.npy",sap)
sap_copy=np.load("sap.npy")
sap_copy

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')